/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 eight_bar_structural_3d_asterisk.glb -T 
Files: eight_bar_structural_3d_asterisk.glb [384.51KB] > /Users/amansinghkaushik/Documents/Portfolio/portfolio/src/assets/models/eight_bar_structural_3d_asterisk-transformed.glb [7KB] (98%)
Author: Firman Maulana Ihsan (https://sketchfab.com/firmaan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eight-bar-structural-3d-asterisk-3f5f3fc73ba34bc496e3f698939c8713
Title: Eight Bar Structural 3D Asterisk
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/eight_bar_structural_3d_asterisk-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_9.geometry} material={materials.material_0} position={[-39.132, 50.009, 31.589]} rotation={[0, Math.PI / 4, -Math.PI]} scale={[-0.333, 0.333, 0.333]} />
    </group>
  )
}

useGLTF.preload('/eight_bar_structural_3d_asterisk-transformed.glb')
